pipeline:
  name: test_cd
  identifier: test_cd
  projectIdentifier: Testcdproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_1
                  identifier: K8sRollingDeploy_1
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    delegateSelectors:
                      - helm-delegate
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: account.sitservice
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: artifact
                          type: DockerRegistry
                          spec:
                            tag: <+input>
          environment:
            environmentRef: account.sit_env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: sit_infra
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - helm-delegate
