pipeline:
  name: Harnesspipeline
  identifier: Harnesspipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Githubconnectorproject
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: install dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: <+input>
              - step:
                  type: Run
                  name: codebuild
                  identifier: codebuild
                  spec:
                    shell: Sh
                    command: <+input>
              - step:
                  type: Run
                  name: unittest
                  identifier: unittest
                  spec:
                    shell: Sh
                    command: <+input>
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnectorproject
                    repo: <+input>
                    tags:
                      - <+input>
